---
kind: pipeline
type: docker
name: linux-amd64

platform:
  arch: amd64
  os: linux

base: /go
path: src/github.com/lochv/srt 
steps:
  
- name: build arm client
  image: golang:1.13.8
  commands:
  - go get golang.org/x/crypto/ssh
  - go get golang.org/x/net/context
  - go build -o ./client.armv5 -a -v -ldflags="-w -s" ./client
  environment:
    GOPATH: /drone
    GOARCH: arm
    GOARM: 5

